### ISSUE TITLE
DFD and DFD Dictionary Comments

### ISSUE THREAD

**Issue by germonprez** [tbonejones/Assignment1-3420#11]
The DFD looks good. Well done. 

Work to get some headers in the Dictionary. 
# H1

**Comment by tbonejones** [comment]
I put headers in the dictionary, I used them for text sizing and as references for links so that terms appearing in the dictionary definitions that are defined elsewhere in the dictionary are clickable links that take you to the term's definition.

**Comment by germonprez** [comment]
Great!
