### ISSUE TITLE
Use Case 1

### ISSUE THREAD

**Issue by germonprez** [tbonejones/Assignment1-3420#21]
1) Do you want to include vulnerabilities in the title? 
2) Are you providing project information (a collection of packages) in your DFD right now? 
3) What are project packages vs. Software Packages? (Success vs. Failed) 
4) Trigger is more about the request from the Manager.

**Comment by tbonejones** [comment]
So, looks like I didn't tailor this use case nearly as well as I thought I did.
1) Added vulnerabilities to the title. Also added it to the process name in DFD and updated dictionary to reflect those changes
2) Don't know why I didn't change that originally, yeah it should be called Software Package and not any of the various things I was referring to it in the use case. Fixed that issue in the use case.
3) Should just be Software Package. Corrected.
4) Made Trigger more about submitting the Software Package Query itself to the Query Process.
Thanks for your help,
Doug
